name: Freeze
main: FreezePlugin
version: 0.0.1-SNAPSHOT
description: Sample of how freezing can be implemented without having clients move on their side
author: Pokechu22
depend: [ProtocolLib]


commands:
  freeze: 
    description: Freeze yourself
    aliases: []
  unfreeze: 
    description: Unfreeze yourself
    aliases: []